lore:
  edit:
    - "&7━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    - ""
    - "&a[!] 구매 가격: &e{buy_price}"
    - "&a[!] 판매 가격: &e{sell_price}"
    - ""
    - "&c[!] &7쉬프트 + 좌클릭: 해당 아이템을 제거합니다."
    - "&c[!] &7쉬프트 + 우클릭: 가격을 설정합니다."
    - ""
    - "&7━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # 열기 GUI 아이템 설정 로어
  open:
    - "&7━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    - ""
    - "&c[!] &7좌클릭/우클릭 &7| &a&l1개 구매/판매"
    - "&c[!] &7쉬프트 + 좌클릭/우클릭 &7| &a&l64개 구매/판매"
    - "&f"
    - "&a[!] &7구매 가격: &f{buy_price}"
    - "&a[!] &7판매 가격: &f{sell_price}"
    - ""
    - "&7━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # 편집 GUI 가격 설정 로어
  edit_price:
    - "&7━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    - ""
    - "&e[!] &7좌클릭 시 구매 가격을 설정합니다."
    - "&e[!] &7우클릭 시 판매 가격을 설정합니다."
    - ""
    - "&7━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"