lore:
  edit:
    - "&a구매 가격: {buy_price}"
    - "&e판매 가격: {sell_price}"
    - "&7웅크리기 + 좌클릭 시 해당 아이템을 제거합니다."
    - "&7웅크리기 + 우클릭 시 가격을 설정합니다."
  open:
    - "&6&l좌클릭 &7| &c&l구매 &6&l우클릭 &7| &a&l판매"
    - "&f"
    - "&7구매 가격: &f{buy_price}"
    - "&7판매 가격: &f{sell_price}"
  edit_price:
    - "&7좌클릭 시 구매 가격을 설정합니다."
    - "&7우클릭 시 판매 가격을 설정합니다."