messages:

  # 접두사
  prefix: '&6[상점] &r'

  # 상점
  shop:

    # 도움말 명령어를 입력했을 때 플레이어에게 출력되는 메세지
    main:
      - ""

    # 도움말 명령어를 입력했을 때 오피에게 출력되는 메세지
    help:
      - "/상점 생성 <상점이름> : 상점을 생성합니다."
      - "/상점 제거 <상점이름> : 상점을 제거합니다."
      - "/상점 열기 <상점이름> : 상점을 엽니다."
      - "/상점 목록 : 상점 목록을 확인합니다."

    # 상점을 생성할 때 출력되는 메세지
    create: "&6{name} &7상점를 생성하였습니다."

    # 상점을 삭제할 때 출력되는 메세지
    delete: "&6{name} &7상점을 삭제하였습니다."

    # 콘피그를 리로드할 때 출력되는 메세지
    reloadConfig: "&a성공적으로 콘피그를 리로드하였습니다."

errorMessages:

  # 상점
  shop:

    # 상점이름을 입력하지 않았을 때 출력되는 메세지
    noName: "&c상점 이름을 입력해주세요."

    # 상점이 이미 존재할 때 출력되는 메세지
    alreadyExist: "&c이미 존재하는 상점입니다."

    # 상점이 존재하지 않을 때 출력되는 메세지
    notExist: "&c존재하지 않는 상점입니다."

    # 상점이름에 특수문자가 포함되어 있을 때 출력되는 메세지
    invalidName: "&c상점 이름에는 특수문자를 사용할 수 없습니다."

  # 권한이 없을 때 출력되는 메세지
  noPermission: "&c당신은 해당 명령어를 사용할 권한이 없습니다."

  # 올바르지 않은 명령어를 입력했을 때 출력되는 메세지
  wrongCommand: "&c명령어 사용법이 올바르지 않습니다."
  