name: ST-Shop
main: net.starly.shop.ShopMain
author: Starly Team
website: http://starly.kr/discord

description: BoilerPlate Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  상점:
