name: ST-Shop
main: net.starly.shop.ShopMain
author: Starly Team
website: http://starly.kr/discord

description: Shop Plugin.

softdepend:
  - ST-Core
  - Vault

version: 1.0_Alpha
api-version: 1.13

commands:
  상점:
    description: 상점 명령어
    aliases: [ shop, 상점 ]