name: ST-Shop
main: net.starly.shop.ShopMain
author: Starly Team
website: http://starly.kr/discord

description: Shop Plugin.

softdepend:
  - ST-Core
  - Vault

version: 1.0.2_Alpha
api-version: 1.14

commands:
  shop:
    aliases: [ 상점 ]